### ISSUE TITLE
Constant signal error message

### ISSUE THREAD

**Issue by qduong42** [Igors78/minitalk#1]
1: Start server in terminal 1
2: Open separate terminal 2
3: Run 
./client [Displayed PID in terminal 1] [string]
in terminal 2
4: Output: Terminal 2:
PID : 53884
Signal error client to server. Restart server

Help would be appreciated :)

**Comment by Igors78** [comment]
![signal](https://user-images.githubusercontent.com/66903652/143266045-882a24a1-b09c-41ad-b050-00b6e177574a.png)
It means the signal is not going through, and kill returns -1 (signal error) Restart machine to lower processes count and try again

**Comment by qduong42** [comment]
Hmm okay but downloading another repo and doing the exact same steps seem to work, so I am not sure the processes count is the issue here.

**Comment by Igors78** [comment]
![test](https://user-images.githubusercontent.com/66903652/143271046-a0015c54-0660-48b8-848a-76db78c28211.png)
